config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts, except: [:show] do
      resources :comments, only: [:create, :destroy]    
  end #show 액션 뺴고 라우팅 해주세요!
  get 'intros/index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments, :dependent => :delete_all  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :comments, :dependent => :delete_all  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_ownership!, only: [:update, :destroy]    
  def create
    new_comment = Comment.new(content: params[:content],
                              post_id: params[:post_id],
                              user_id: current_user.id)
    new_comment.save

    redirect_to :back
  end
 
  def destroy
    @comment.destroy
    redirect_to :back
  end
  
   private
  def check_ownership!
    @comment = Comment.find_by(id: params[:id])
    redirect_to root_path if @comment.user.id != current_user.id
  end 
end

app/controllers/intros_controller.rb
class IntrosController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :check_ownership, only: [:destroy]

  def index
      @posts = Post.all.order('created_at desc')    
  end
  
  def create
      new_post = Post.new(name: params[:name], password: params[:password], content: params[:content])
      if new_post.save
        redirect_to root_path
      else
        redirect_to new_post_path
      end    
      
  end
  
  def new
  end
  
  def edit
  end  
  
  def destroy
     @post.destroy
     redirect_to root_path
  end  

  def check_ownership
      @post = Post.find_by(id: params[:id])
      @password = params[:password]
      if (current_user==nil) && (@post.password != @password)
          redirect_to posts_path
      elsif (current_user!=nil) && (current_user.email!="donsdev@insomenia.com") 
         redirect_to posts_path
      end     
  end   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/intros_helper.rb
module IntrosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/intros/index.html.erb
<div class="container">
    <div class="row">
        <div class="col s0 m2"></div>
        <div class="col s12 m8 center">
            <%= image_tag("profileimg.png", class: "responsive-img circle introimage") %>      
            <h5 class="introname">김도현입니다</h5>
            <p class="introtext">여러분 열심히 꾸며주세요!</h5> 
            <p class="contact1">kakao : donsworkout</p>
            <p class="contact2">insta : @donsworkout</p>
            <ul class="collapsible" style="margin-bottom:60px;">
              <li>
                <div class="collapsible-header">
                  <i class="material-icons">android</i>
                  코딩 잘해요?
                  <span class="new badge"></span></div>
                <div class="collapsible-body"><p>노력하고 있습니다</p></div>
              </li>
              <li>
                <div class="collapsible-header">
                  <i class="material-icons">place</i>
                  저는 어디 살까요?
                  <span class="badge">1</span></div>
                <div class="collapsible-body"><p>상수역에서 자취해요!</p></div>
              <li>
                <div class="collapsible-header">
                  <i class="material-icons">attach_money</i>
                  이거 코딩하는데 얼마나 걸렸어요?
                  <span class="badge">1</span></div>
                <div class="collapsible-body"><p>5시간이요!</p></div>
              </li>
              </li>
            </ul>
        </div>
        <div class="col s0 m2"></div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>심심한 도현이</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta property="og:title" content="심심한 도현이에게">
  <meta property="og:description" content="오늘도 심심한 도현이에게 한마디를!">
  <meta property="og:image" content="https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/29572603_2037752239799265_192703282482811636_n.png?_nc_cat=0&oh=1e811c4b13cf22b1e18cb5a5a749b76d&oe=5B4032BD">
</head>
<body>
  <nav>
    <div class="nav-wrapper  red lighten-3">
      <div class="container">
        <a href="/" class="brand-logo">도현이에게</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="/" class="nav-link">안부 타임라인</a></li>
          <li><a href="/posts/new" class="nav-link">새 안부 쓰기</a></li>
          <li><a href="/intros/index" class="nav-link">나?</a></li>
          <% if !user_signed_in? %>
            <li><a href="/users/sign_in" class="nav-link">로그인</a></li>     
          <% else %>
            <li><%= link_to '로그아웃', destroy_user_session_path, class: ""%></li>           
          <% end %>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><a href="/" class="nav-link">안부 타임라인</a></li>
          <li><a href="/posts/new" class="nav-link">새 안부 쓰기</a></li>
          <li><a href="/intros/index" class="nav-link">나?</a></li>
          <% if !user_signed_in? %>
            <li><a href="/users/sign_in" class="nav-link">로그인</a></li>     
          <% else %>
            <li><%= link_to '로그아웃', destroy_user_session_path, class: ""%></li>           
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  
    <%= yield %>
    
</body>
</html>

<script>
  $(document).ready(function() {
    $(".button-collapse").sideNav();
});
</script>

app/views/posts/index.html.erb
<div class="banner1" id="banner1">
    <div class="banner1_text center">
        <p class="bt1">오늘도 심심한 도현이에게</p>
        <p class="bt2">안부를 물어주세요!</p>
    </div>
    <div class="banner1_btn center">
        <a href="/posts/new" class="waves-effect waves-light btn red lighten-3 center btnban">안부묻기</a>
    </div>
</div> 

<div class="container">
    <div class="row">
        <div class="col s0 m2">
    
        </div>
        <div class="col s12 m8">
            <% if @posts %>
                <% @posts.each do |post| %>
                    <div class="card" style="margin-bottom:40px;">
                        <a class="modal-trigger right" href="#modal<%=post.id%>">
                            <i class="material-icons mycon">close</i>
                        </a>
                        <div class="card-content">
                            <p class="card-title">안녕, 난 <%=post.name%>!😏</p>
                            <span class="new badge left red accent-1" style="margin-left:0px;" data-badge-caption="<%=post.created_at.strftime("%Y년 %m월 %d일 %H시쯤")%>"></span>
                            <br><br>
                            <p class="cardtext"><%= simple_format(post.content) %></p>
                            <br>
                                        <br>
                                        <% if post.comments.present? %>
                                            <ul class="collection">
                                                <% post.comments.each do |comment| %>
                                                    <li class="collection-item" style="margin-top:20px;">
                                                        <% if user_signed_in? && comment.user.id == current_user.id %>
                                                            <%= link_to post_comment_path(post, comment), method: "delete", class: "right",:data => {:confirm => '정말 삭제하실 건가요?'} do %>
                                                                <i class="material-icons mycon">close</i>                                                          
                                                            <% end %>
                                                        <% end %> 
                                                        <p class="comuser">반가워, 난 <%= comment.user.name %>😀</p>
                                                        <br>
                                                        <p class="comcont"><%= comment.content %></p>
                                                        <br>
                                                    </li>
                                                <% end %>
                                            </ul>
                                        <% end %> 
                        </div>
                        <% if user_signed_in? && current_user.email == "donsdev@insomenia.com"%>
                            <ul class="collapsible">
                                <li>
                                    <div class="collapsible-header"><i class="material-icons">comment</i>답장하기</div>
                                    <div class="collapsible-body">
                                        <%= form_tag post_comments_path(post) do %>
                                            <div class="input-field smaller">
                                                <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "답장을 남겨주세요", required: true %>
                                            </div>
                                            <div class="input-field center">
                                                <%= button_tag "답장 쓰기", class: "btn small red lighten-3" %>
                                            </div>
                                        <% end %>     
                                    </div>
                                </li>
                            </ul>
                        <% end %>
                    </div>
                    
                    <div id="modal<%=post.id%>" class="modal">
                        <%= form_tag post_path(post), method: "delete" do %>
                            <div class="modal-content">
                                <h5>정녕 지우십니까? ㅠㅠ</h5>
                                <br>
                                <%= password_field_tag :password, nil ,class: "form-control tarea", placeholder: "비밀번호" %>  
                            </div>
                            <div class="modal-footer">
                                <%= button_tag "삭..제", class: "waves-effect waves-light btn orange"%>
                                <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">취소</a>
                            </div>
                          <% end %>
                    </div>
                      
                <% end %>
            <% end %>
        <div class="col s0 m2">
    
        </div>
    </div>
    
</div>


<script>
  $(document).ready(function(){
    $('.modal').modal();
  });
</script>

app/views/posts/new.html.erb
<div class="banner1" id="banner1">
    <div class="banner1_text center">
        <p class="bt1">오늘도 심심한 도현이에게</p>
        <p class="bt2">새 안부 묻기</p>
    </div>
</div> 
<div class="container">
  <br>
  <div class="row">
    <div class="col s0 m2 l3"></div>
    <div class="card col s12 m8 l6">
      <div class="card-content">
        <br><br>
        <div class="card-title center">예쁜말 고운말만 써주세요 :)</div>
        <br><br>
        <%= form_tag posts_path, multipart: true do %>
          <div class="row">
              <div class="input-field col s12 m6">
                <%= text_field_tag :name, nil, class: "materialize-textarea", id: "name"%>
                <label for="name">당신을 표현해줄 닉네임</label>
              </div>
              <div class="input-field col s12 m6">
                <%= password_field_tag :password, nil, class: "materialize-textarea", id: "name", required: true %>
                <label for="name">비밀번호 (4자리 이상)</label>
              </div>
          </div>

          <div class="row">
              <div class="input-field col s12">
                <%= text_area_tag :content, nil, class: "materialize-textarea", id: "content" %>
                <label for="content">안부를 곱게(?) 전해봐요</label>
              </div>
          </div>
          <div class="input-field">
            <div class="center">
              <%= button_tag "작성하기", class: "btn red lighten-2" %>
            </div>
          </div>
          <br><br>
        <% end %>
      </div>
    </div>
    <div class="col s0 m2 l3"></div>
  </div>
</div>